solver:
    - alphacsc:
        type: batch
    - sporco
    - rosecdl:
        n_csc_iterations: 50
        sample_window: [10, 20, 50]  # This is scaled with the atom size
        mini_batch_size: [8, 16, 32]  # This is scaled with the atom size

dataset:
    - simulated:
        n_samples: [10, 20, 50, 100]  # , 200, 500, 1000, 2000]
        n_times: [1000, 2000, 5000]  # , 10000, 20000, 50000]
        n_atoms: 5  # We use n_atoms to generate data and add 5 for the CDL
        n_times_atom: 50
        random_state: [42]  # [93845, 92384, 2389, 230984, 234890]
        contamination: 0
