solver:
    - alphacsc:
        type: batch
        epochs: 1000
    - sporco
    - wincdl:
        epochs: 1000
        n_csc_iterations: 25

dataset:
    - simulated:
        n_samples: [10, 20, 50, 100, 200, 500, 1000, 2000]
        n_times: [1000, 2000, 5000, 10000, 20000, 50000]
        n_atoms: 10
        n_times_atom: 50
        random_state: 42
        contamination: 0
