solver:
    - alphacsc:
        type: batch
    - sporco
    - wincdl

dataset:
    - simulated:
        n_samples: [10, 20, 50, 100, 200, 500, 1000, 2000]
        n_times: [1000, 2000, 5000, 10000, 20000, 50000]
        n_atoms: 2
        n_times_atom: 50
        random_state: 42
        contamination: 0

objective:
    - "Convolutional Dictionary Learning":
        reg: 0.3