objective:
  - RoseCDL:
        reg: [0.8]
solver:
    - alphacsc:
        type: batch
    - sporco
    - rosecdl:
        n_csc_iterations: 50
        sample_window: [50]  # This is scaled with the atom size
        mini_batch_size: 10  # This is scaled with the atom size
dataset:
    - simulated:
        n_samples: [10]
        n_times: [5000, 10000]
        n_atoms: 5  # We use n_atoms to generate data and add 5 for the CDL
        n_times_atom: 50
        random_state: [93845, 92384, 2389, 230984, 234890]
        contamination: True
timeout: 1800
max-runs: 5000
output: benchmark_outliers
