# This experiment evaluates the robustness of RoseCDL to noise, and
# makes sure the runtime using SLS is not impacted by high noise levels.
# Runs RoseCDL with Adam and SLS, for 3 noise levels, with 5 seeds.
solver:
    - alphacsc:
        outliers_kwargs:
        type: batch
    - sporco:
        outliers_kwargs:
    - rosecdl:
        outliers_kwargs:
        n_csc_iterations: 50
        optimizer: [linesearch]
        sample_window,mini_batch_size: [
            [8, 8]
        ]
objective:
    - RoseCDL:
        reg: [0.1]
dataset:
    - simulated:
        n_samples: [2]
        n_times: [512]
        # We use n_atoms to generate data and add 5 to run CDL,
        # making it possible to recover them. So in total, RoseCDL
        # runs with 10 atoms.
        n_atoms: 2
        n_times_atom: 32
        random_state: [42]
        noise_std: [0.01]
        contamination: False
timeout: 30
max-runs: 100
