name: Tests

on:
  push:
    branches:
      - main
  create:
    tags:
      - '**'
  pull_request:
    branches:
      - main
  schedule:
    # Run every day at 7:42am UTC.
    - cron:  '42 7 * * *'

jobs:
  benchopt_dev:
    uses: tommoral/template_benchmark/.github/workflows/test_benchmarks.yml@ENH_allow_running_CI_from_subfolders
    with:
      benchopt_branch: benchopt@main
      benchmark_dir: benchmark
  benchopt_release:
    uses: tommoral/template_benchmark/.github/workflows/test_benchmarks.yml@ENH_allow_running_CI_from_subfolders
    with:
      benchopt_version: latest
      benchmark_dir: benchmark
  lint:
    uses: benchopt/template_benchmark/.github/workflows/lint_benchmarks.yml@main
